application/forms/add_user.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, EmailField, SubmitField, StringField
from wtforms.validators import DataRequired

class AddUser(FlaskForm):
    """[Form to add user]
    """
    lastname = StringField(label='Nom', validators=[DataRequired()])
    firstname = StringField(label='Prénom', validators=[DataRequired()])
    email = EmailField(label='Email', validators=[DataRequired()])
    password_hash = PasswordField(label='Mot de passe', validators=[DataRequired()])
    password_hash2 = PasswordField(label='Confirmez votre mot de passe', validators=[DataRequired()])
    submit = SubmitField(label='Ajouter')

application/forms/login.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, EmailField, SubmitField
from wtforms.validators import DataRequired

class Login(FlaskForm):
    """[Form to login]
    """
    email = EmailField(label="Adresse mail:", validators=[DataRequired()])
    password = PasswordField(label="Mot de passe:",
                             validators=[DataRequired()])
    submit = SubmitField(label="Login")
    
    

application/forms/prediction.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, IntegerField
from wtforms.validators import DataRequired, Length, NumberRange
from wtforms.fields import SelectField
import datetime 

max_year = datetime.datetime.today().year + 1

class PredictionForm(FlaskForm):
    """Form for prediction
    """
    overall_qual = IntegerField(label='Qualité générale', validators=[
        DataRequired() , NumberRange(min=0, max=11, message="Value must be between 0 and 5")], default=5)
    
    neighborhood = SelectField(label='Quartier', validators=[
        DataRequired()], choices=['NAmes', 'Gilbert', 'StoneBr', 'NWAmes', 'Somerst', 'BrDale',
                                'NPkVill', 'NridgHt', 'Blmngtn', 'NoRidge', 'SawyerW', 'Sawyer', 'Greens', 'BrkSide', 
                                'OldTown', 'IDOTRR', 'ClearCr', 'SWISU', 'Edwards', 'CollgCr', 'Crawfor', 'Blueste', 
                                'Mitchel', 'Timber', 'MeadowV', 'Veenker', 'GrnHill', 'Landmrk'] , default="NAmes")
    
    year_remod_add = IntegerField(label='Année de construction ou renovation', validators=[
        DataRequired(), NumberRange(min=1800, max=max_year, message=f"Year must be between 1800 and {max_year}")], default=2020)
    
    exterior_1st = SelectField(label='Métériaux extérieur', validators=[
        DataRequired()], choices=['BrkFace', 'VinylSd', 'Wd Sdng', 'CemntBd', 'HdBoard', 'Plywood',
                                'MetalSd', 'AsbShng', 'WdShing', 'Stucco', 'AsphShn', 'BrkComm',
                                'CBlock', 'PreCast', 'Stone', 'ImStucc'] , default="BrkFace")
    
    bsmt_qual = SelectField(label='Hauteur du sous-sol', validators=[
        DataRequired()], choices=['Ex', 'Gd', 'TA', 
                                  'Fa', 'Po (<70 inches)' 'NA'], default="NA")
    
    exter_qual = SelectField(label='Qualité extérieur', validators=[
        DataRequired()], choices=['Ex', 'Gd', 'TA', 'Fa'], default="TA")
    
    kitchen_qual = SelectField(label='Qualité de la cuisine', validators=[
        DataRequired()], choices=['Ex', 'Gd', 'TA', 'Fa', 'Po'], default="TA")
    
    garage_qual = SelectField(label='Qualité du garage', validators=[
        DataRequired()], choices=['TA', 'Fa', 'Gd', 'Ex', 'Po', 'No garage'], default="Ex")
    # Ajouter dictionnaire pour No garage en np.nan 
    
    fireplaces = IntegerField(label='Nombre de cheminée', validators=[
        DataRequired(), NumberRange(min=0, message=f"Entre 0 et infinie")], default=0)
    
    fireplace_qu = SelectField(label='Qualité du garage', validators=[
        DataRequired()], choices=['Gd', "No fireplace", 'TA', 'Po', 'Ex', 'Fa'], default="Ex")
    # Ajouter np.nan en dictionnaire à la place du no fireplace
    
    full_bath = IntegerField(label='Nombre de salle de bain complète', validators=[
        DataRequired(), NumberRange(min=0, message=f"Entre 0 et infinie")], default=0)
    
    half_bath = IntegerField(label='Nombre de demi salle de bain', validators=[
        DataRequired(), NumberRange(min=0, message=f"Entre 0 et infinie")], default=0)
    
    bsmt_full_bath = IntegerField(label='Nombre de salle de bain complète au sous-sol', validators=[
        DataRequired(), NumberRange(min=0, message=f"Entre 0 et infinie")], default=0)
    
    bsmt_half_bath = IntegerField(label='Nombre de demi salle de bain au sous-sol', validators=[
        DataRequired(), NumberRange(min=0, message=f"Entre 0 et infinie")], default=0)
    
    utilities = SelectField(label='Eau et éléctricité', validators=[
        DataRequired()], choices=['AllPub', 'NoSewr', 'NoSeWa'], default="AllPub")
    
    gr_liv_area = IntegerField(label='Surface habitable en m2', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=50)
    
    total_bsmt_sf = IntegerField(label='Surface de la cave en m2', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=150)
    
    first_flr_sf = IntegerField(label='Surface du 1er étage en m2', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=150)
    
    second_flr_sf = IntegerField(label='Surface du 2ème étage en m2', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=150)
    
    open_porch_sf = IntegerField(label='Surface du porche', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=150)
    
    wood_deck_sf = IntegerField(label='Surface terasse en bois', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=0)
    
    pool_area = IntegerField(label='Surface piscine', validators=[
        DataRequired(), NumberRange(min=0, message="Negative value is not possible")], default=0)
    
    heating_qc = SelectField(label='Qualité du chauffage', validators=[
        DataRequired()], choices=['Ex', 'Gd', 'TA', 'Fa', 'Po'], default="TA")
    
    bsmt_exposure = SelectField(label='Qualité murs rez-de-chaussée ou jardin', validators=[
        DataRequired()], choices=['Gd', 'No', 'Mn', 'Av'], default="No")
    
    paved_drive = SelectField(label='Chemin pavé ou gravié', validators=[
        DataRequired()], choices=['P', 'Y', 'N'], default="P")
    
    street = SelectField(label='Rue pavé ou gravié', validators=[
        DataRequired()], choices=['Pave', 'Grvl'], default="Pave")
    
    central_air = SelectField(label='Rue pavé ou gravié', validators=[
        DataRequired()], choices=['Y', 'N'] , default="N")
    
    condition_1 = SelectField(label='Proximité axes routiers', validators=[
        DataRequired()], choices=['Norm', 'Feedr', 'PosN', 'RRNe', 'RRAe', 'Artery', 'PosA', 'RRAn', 'RRNn'], default="Norm")
    
    condition_2 = SelectField(label='Proximité axes routiers', validators=[
        DataRequired()], choices=['Norm', 'Feedr', 'PosA', 'PosN', 'Artery', 'RRNn', 'RRAe', 'RRAn'], default="Norm")
    
    garage_cars = IntegerField(label="Nombre de voiture entrant dans le garage", validators=[
        DataRequired() , NumberRange(min=0, message="Negative value is not possible")], default=0)
    
    garage_area = IntegerField(label="Surface du garage en m2", validators=[
        DataRequired() , NumberRange(min=0, message="Negative value is not possible")], default=55)
    
    garage_finish = SelectField(label="Qualité de l'exterieur", validators=[
        DataRequired()], choices=['Fin', 'Unf', 'RFn'] , default="Fin")
    
    sale_condition = SelectField(label="Qualité de l'exterieur", validators=[
        DataRequired()], choices=['Normal', 'Partial', 'Family', 'Abnorml', 'Alloca', 'AdjLand'], default="Ex")
    
    submit = SubmitField(label='prediction')

application/routes/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from application.forms.login import Login
from application.forms.add_user import  AddUser
from application.database.users import User
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user

auth = Blueprint('auth', __name__, url_prefix='/')

@auth.route('/')
def home():
    return render_template('home.html')

@auth.route("/login", methods=["GET","POST"])
def login():
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            login_user(user)
            flash("Logged in with success", category="success")
            print("un user s'est connecté")
            return redirect(url_for('auth.home'))
        else:
            flash("Mail address or password invalid", category="danger")
    return render_template('login.html', form=form)


@auth.route('/add_user', methods= ['GET', 'POST'])
def add_user():
    form = AddUser()
    if form.validate_on_submit():
        if form.password_hash.data == form.password_hash2.data:

            check = User.query.filter_by(email = form.email.data).first()
            if check : 
                flash('Email already exists', category='error')
                return redirect(url_for('auth.login'))
            User(lastname = form.lastname.data, firstname = form.firstname.data, email = form.email.data, password_hash = generate_password_hash(form.password_hash.data, method='sha256')).save_to_db()
            flash('Nouvel utilisateur ajouté ', category='secondary')
            return redirect(url_for('auth.login'))
        else:
            flash('Please enter same password')
    return render_template('add_user.html', form=form)

@auth.route('/logout')
def logout_page():
    logout_user()
    flash('Vous êtes correctement déconnecté',category="success")
    return redirect(url_for('auth.login'))

application/routes/prediction.py
from flask import Blueprint, render_template, request
from flask_login import current_user
import pandas as pd
import joblib
from application import db 
from application.forms.prediction import  PredictionForm
from application.database.prediction import Prediction
from application.helpers.preprocessing import (data_engineering, data_preprocessing, features_selection, neighbors_dict, 
                                               conditions_dict, sale_condition_dict, clean_columns)

model = joblib.load(open('model/fit/model.joblib', 'rb'))
prediction = Blueprint('prediction', __name__, url_prefix='/prediction')

@prediction.route('/')
def index():
    return render_template('prediction.html', form=PredictionForm())

@prediction.route('/predict', methods=['GET', 'POST'])
def predict():
    form = PredictionForm()
    keys = [i for i in form._fields if i not in ['submit', 'csrf_token']]
    pred = 0
    if form.submit():
        print(keys)
        dict_prediction = {}
        for var in keys:
            dict_prediction[var]= form[var].data
        df_prediction = pd.DataFrame(dict_prediction, index=[0])
        df_prediction = features_selection(data_engineering(data_preprocessing(clean_columns(df_prediction), neighbors_dict, conditions_dict, sale_condition_dict)))
        pred = int(model.predict(df_prediction))
        dict_prediction['price'] = pred
        Prediction(**dict_prediction, user_id=current_user.id).save_to_db()
    return render_template('prediction.html', data=f'{pred} $', form=form)



@prediction.route('/history', methods=['GET','POST'])
def history():
    prediction_id = request.args.get('id')
    print(prediction_id)
    if prediction_id:
        Prediction.query.filter(Prediction.id == prediction_id).first().delete_from_db()
        print("user deleted")
    predictions = db.session.query(Prediction).where(Prediction.user_id == current_user.id).all()
    return render_template('history.html', predictions=predictions)
    

application/templates/add_user.html
{% extends "base.html" %}
{% block title %}
Ajout utilisateur
{% endblock %}
{% block content%}

<div class='main1'>
    <h1>Nouvel utilisateur</h1>
    <form method="POST" class="main1">
        {{ form.hidden_tag() }}

        {{ form.firstname.label }}
        {{ form.firstname(size=32, class="form-control") }}
        <br>

        {{ form.lastname.label }}
        {{ form.lastname(class="form-control") }}
        <br>

        {{ form.email.label }}
        {{ form.email(size=32, class="form-control") }}
        <br>

        {{ form.password_hash.label }}
        {{ form.password_hash(class="form-control") }}
        <br>


        {{ form.password_hash2.label }}
        {{ form.password_hash2(class="form-control") }}
        <br>

        {{ form.submit(class="btn btn-lg btn-dark mt-4 d-block",id="button") }}
    </form>
</div>


<div class='main2 idx-10'>
    <h1>Mot de pass oublié </h1>
    <form method="POST" class="main1">
        {{ form.hidden_tag() }}

        {{ form.lastname.label }}
        {{ form.lastname(size=32, class="form-control") }}
        <br>

        {{ form.firstname.label }}
        {{ form.firstname(class="form-control") }}
        <br>

        {{ form.email.label }}
        {{ form.email(size=32, class="form-control") }}
        <br>


        {{ form.submit(class="btn btn-lg btn-dark mt-4 d-block",id="button") }}
    </form>
</div>

<div class="main3"></div>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap pour flask login -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <!-- CSS -->
  <link rel="stylesheet" href="/static/css/grid.css">

  <title>
    {% block title %}
    {% endblock %}
  </title>

</head>

  <nav>
    <ul>
      <a aria-current="page" href="{{ url_for('auth.home') }}">Home</a>
      {% if current_user.is_authenticated %}
      <a class="nav-link" href="{{ url_for('prediction.index') }}">Prediction</a>
      <a class="nav-link" href="{{ url_for('prediction.history') }}">Watch history</a>
      <a class="nav-link" href="{{ url_for('auth.logout_page') }}">Log out</a>
      {% else %}
      <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
      <a class="nav-link" href="{{ url_for('auth.add_user') }}">Create an account</a>
      {% endif %}
    </ul>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category,message in messages %}
    <div class="alert alert-{{ category }} alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </nav>
  
  <body class="main">
  {% block content %}
  {% endblock %}
</body>

  <div class="foot">
    <div>
      <h5 class="white align pa-8">Contact</h5>
    </div>
  </div>

</html>

application/templates/history.html
{% extends "base.html" %} {% block title %} {% endblock %} {% block content %}



<table id="data" class="table table-striped align">
    <thead>
      <tr>
        <th>Year_Built</th>
        <th>Total_Bsmt_SF</th>
        <th>Frst_Flr_SF</th>
        <th>Gr_Liv_Area</th>
        <th>Overall_Qual</th>
        <th>Full_Bath</th>
        <th>Exter_Qual</th>
        <th>Kitchen_Qual</th>
        <th>Neighborhood</th>
        <th>Price</th>
        <th>Created_on</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for prediction in predictions %}
        <tr>
          <td>{{ prediction.year_remod_add }}</td>
          <td>{{ prediction.total_bsmt_sf }}</td>
          <td>{{ prediction.first_flr_sf }}</td>
          <td>{{ prediction.gr_liv_area }}</td>
          <td>{{ prediction.overall_qual }}</td>
          <td>{{ prediction.full_bath }}</td>
          <td>{{ prediction.exter_qual }}</td>
          <td>{{ prediction.kitchen_qual }}</td>
          <td>{{ prediction.neighborhood }}</td>
          <td>{{ prediction.price }}</td>
          <td>{{ prediction.created_on }}</td>
          <td> <a href="{{ url_for('prediction.history', id=prediction.id)}}"> Delete </a></td>
        </tr>
      {% endfor %}


{% endblock %}

application/templates/home.html
{% extends "base.html" %} {% block title %} {% endblock %} {% block content %}

<div class="main1">
  {% if current_user.is_authenticated %}
  <h1>Welcome {{ current_user.fisrtname}} {{current_user.lastname }}</h1>
  {% else %}
  <h1>Welcome to my website project</h1>
  {% endif %}
  <p>House pricing prediction and more</p>
</div>

<div class="main2">

  
  <div class="rowflex">

    <img src="{{url_for('static', filename='img.jpg')}}" align="middle" class="home-img"/>
  </div>
</div>

<div class="main3"> </div>

{% endblock %}

application/templates/login.html
{% extends "base.html" %} {% block title %} {% endblock %} {% block content %}

<div class="main1">
  {% if current_user.is_authenticated %}
  <h1>Welcome {{ current_user.fisrtname}} {{current_user.lastname }}</h1>
  {% else %}
  <h1>Welcome to my website project</h1>
  {% endif %}
  <p>House pricing prediction and more</p>
</div>

<div class="main2">

  
  <div class="rowflex">

    {% if current_user.is_authenticated %}
    <img src="{{url_for('static', filename='img.jpg')}}" align="middle" class="home-img"/>
    {% else %}

    <form method="POST" class="form-register">
      <div>{{ form.hidden_tag() }}</div>
      <div class="form-inside">
        <div class="email">
          <div class="email-label">Email:</div>
          {{form.email(placeholder="exemple@exemple.com",
          class="form-control")}}
        </div>
        <div class="password">
          <div class="password-label">Password:</div>
          {{form.password(placeholder="***********", class="form-control")}}
        </div>

        <div class="rowflex">
          <div class="element">
            {{ form.submit(class="btn bouton", id="button")}}
          </div>
          <div class="element">
            <a href="{{ url_for('auth.add_user') }}">Register</a>
          </div>
        </div>
      </div>
    </form>
    {%endif%}
  </div>
</div>

<div class="main3"> </div>



{% endblock %}

application/templates/prediction.html
{% extends "base.html" %}
{% block title %}
{% endblock %}

{% block content %}


<div class="prediction form-sider ">
    <div class="prediction ">
        <h1 class="pred-title">Prediction</h1>
  

            <form action="{{url_for('prediction.predict')}}" method="POST" class="">
            {{ form.hidden_tag() }}

            {{ form.overall_qual.label(class="align")}}
            {{ form.overall_qual(placeholder="Quelle est l'année de construction?", class="form-control") }}
            
            {{ form.neighborhood.label()}}
            {{ form.neighborhood(placeholder="", class="form-control") }}
            
            {{ form.year_remod_add.label()}}
            {{ form.year_remod_add(placeholder="", class="form-control") }}

            {{ form.exterior_1st.label()}}
            {{ form.exterior_1st(placeholder="", class="form-control") }}

            {{ form.bsmt_qual.label()}}
            {{ form.bsmt_qual(placeholder="", class="form-control") }}

            {{ form.exter_qual.label()}}
            {{ form.exter_qual(placeholder="", class="form-control") }}

            {{ form.kitchen_qual.label()}}
            {{ form.kitchen_qual(placeholder="", class="form-control") }}

            {{ form.garage_qual.label()}}
            {{ form.garage_qual(placeholder="", class="form-control") }}

            {{ form.fireplaces.label()}}
            {{ form.fireplaces(placeholder="", class="form-control") }}
            
            {{ form.fireplace_qu.label()}}
            {{ form.fireplace_qu(placeholder="", class="form-control") }}
            
            </div>
            <div class="prediction  ">

                {{ form.half_bath.label(class="align")}}
                {{ form.half_bath(placeholder="Quelle est l'année de construction?", class="form-control") }}
                
                {{ form.bsmt_full_bath.label()}}
                {{ form.bsmt_full_bath(placeholder="", class="form-control") }}
                
                {{ form.bsmt_half_bath.label()}}
                {{ form.bsmt_half_bath(placeholder="", class="form-control") }}
    
                {{ form.utilities.label()}}
                {{ form.utilities(placeholder="", class="form-control") }}
    
                {{ form.gr_liv_area.label()}}
                {{ form.gr_liv_area(placeholder="", class="form-control") }}
    
                {{ form.total_bsmt_sf.label()}}
                {{ form.total_bsmt_sf(placeholder="", class="form-control") }}
    
                {{ form.first_flr_sf.label()}}
                {{ form.first_flr_sf(placeholder="", class="form-control") }}
    
                {{ form.second_flr_sf.label()}}
                {{ form.second_flr_sf(placeholder="", class="form-control") }}
    
                {{ form.open_porch_sf.label()}}
                {{ form.open_porch_sf(placeholder="", class="form-control") }}
                
                {{ form.wood_deck_sf.label()}}
                {{ form.wood_deck_sf(placeholder="", class="form-control") }}
                
            </div>

            <div class="prediction  ">

                {{ form.pool_area.label(class="align")}}
                {{ form.pool_area(placeholder="Quelle est l'année de construction?", class="form-control") }}
                
                {{ form.heating_qc.label()}}
                {{ form.heating_qc(placeholder="", class="form-control") }}
                
                {{ form.bsmt_exposure.label()}}
                {{ form.bsmt_exposure(placeholder="", class="form-control") }}
    
                {{ form.paved_drive.label()}}
                {{ form.paved_drive(placeholder="", class="form-control") }}
    
                {{ form.street.label()}}
                {{ form.street(placeholder="", class="form-control") }}
    
                {{ form.central_air.label()}}
                {{ form.central_air(placeholder="", class="form-control") }}
    
                {{ form.condition_1.label()}}
                {{ form.condition_1(placeholder="", class="form-control") }}
    
                {{ form.condition_2.label()}}
                {{ form.condition_2(placeholder="", class="form-control") }}
    
                {{ form.garage_cars.label()}}
                {{ form.garage_cars(placeholder="", class="form-control") }}
                
                {{ form.garage_area.label()}}
                {{ form.garage_area(placeholder="", class="form-control") }}
                
                {{ form.submit(class="form-control red ma-2")}}
            </div>

                </form>
    </div>
</div>

<div class="result">
    <h1>Estimation</h1>
    <p class="result-data"> <br> {{data }} </p>
</div>


{% endblock %}